export const API_STATES = {
	LOADING: 'LOADING',
	SUCCESS: 'SUCCESS',
	ERROR: 'ERROR',
};

export const cardData = [
  {
    "id": "60397b392c42a6e9664ed608",
    "name": "Gracker expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Misty Shields",
    "description": "Ad cupidatat non cillum eiusmod amet consectetur dolor officia nisi aliquip labore sint est sit. Ea exercitation veniam amet non labore velit sunt aliqua Lorem consectetur. Duis incididunt ad ea amet in cupidatat. Nisi ea duis irure culpa ex. Mollit reprehenderit consequat mollit in Lorem. Non reprehenderit officia ut commodo cupidatat incididunt occaecat cupidatat qui ex fugiat aute est commodo. Adipisicing consequat dolor pariatur excepteur in nisi sint labore adipisicing enim.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b395053be880061653b",
    "name": "Recritube expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Becker Marks",
    "description": "Do ipsum et consequat occaecat consequat consectetur consequat. Aliqua aute voluptate elit sunt ea esse. Laboris reprehenderit aute Lorem tempor laborum consectetur. Qui non labore eu elit adipisicing dolor non laboris officia adipisicing velit. Cupidatat eu ad est excepteur culpa ea sit voluptate incididunt ipsum culpa sit in duis.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39334a22e4cd2588ee",
    "name": "Zillar expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Glenna Clarke",
    "description": "Lorem ea eu nulla eu id do commodo. Amet dolore in ipsum ut eu cupidatat aliquip proident reprehenderit cillum minim id. In incididunt cupidatat exercitation nisi.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3919dab6d427146529",
    "name": "Geostele expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Holland Boyer",
    "description": "Reprehenderit deserunt ullamco adipisicing mollit duis labore sunt tempor. Non in sit aliqua duis qui dolor. Deserunt do ut nisi incididunt ea ex minim non dolore incididunt nostrud.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b399f820b7376f8d9ff",
    "name": "Scenty expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Wolf Kerr",
    "description": "Voluptate eu incididunt ut sunt excepteur. Est nulla consectetur incididunt eu culpa esse ullamco. Occaecat mollit occaecat occaecat non laborum velit dolore do id est.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b396e04baaff18488b4",
    "name": "Memora expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Rene Whitfield",
    "description": "Id culpa cillum Lorem et laborum sint fugiat labore magna sunt amet. Non sit velit laboris in laboris laborum deserunt consectetur labore. Esse quis dolore ea Lorem minim non dolore velit consequat. Laboris sit id elit quis sit commodo aliquip eiusmod est officia consequat occaecat. Deserunt velit culpa ullamco in nisi exercitation nulla. Officia laborum minim cillum ut sunt nisi aute veniam laborum nisi est deserunt nulla enim.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39ada330a10b83ef64",
    "name": "Knowlysis expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Abbott Alexander",
    "description": "Amet veniam proident elit laborum. Id irure incididunt exercitation quis laboris aliquip duis. Anim cillum eiusmod non velit enim velit elit nostrud cupidatat ex tempor ut voluptate. Magna id nostrud reprehenderit et. Amet laborum proident commodo tempor. Nulla aliquip ut do magna est pariatur dolore eiusmod elit anim labore dolor tempor. Ex velit commodo nostrud ea incididunt eu.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b394623d0f60b475ca5",
    "name": "Vendblend expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Annmarie Ochoa",
    "description": "Lorem amet tempor velit non nulla velit labore sint ut consequat pariatur et excepteur officia. Est in laboris irure cillum sit ea proident deserunt magna anim. Id ipsum proident aute aliquip eiusmod voluptate ad deserunt ex culpa. Adipisicing cupidatat proident aute occaecat commodo minim ut ex amet sint ipsum. Sit labore elit occaecat laborum irure irure. Non proident adipisicing veniam cupidatat fugiat amet.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3960df27c2fc20eed9",
    "name": "Turnabout expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Manning Durham",
    "description": "Nulla in do dolore aute excepteur aute irure minim eiusmod veniam tempor fugiat elit consequat. Do ea dolore cillum laboris. Fugiat et ut id tempor aliquip esse. Aliqua nostrud anim dolore pariatur eiusmod eiusmod fugiat cupidatat aliquip nisi veniam nisi sint occaecat. Do minim officia aute cupidatat sunt ex velit sunt ex esse nisi aute adipisicing elit. Sunt consequat esse tempor irure velit et aute proident esse tempor. Et nisi magna ipsum consectetur duis.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39492ff8dd013decf7",
    "name": "Architax expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Ashlee Kane",
    "description": "Qui ex nostrud tempor officia duis enim incididunt tempor pariatur dolore veniam tempor eu. Nulla pariatur Lorem proident ad elit ullamco pariatur ut. Pariatur esse minim sit excepteur excepteur deserunt enim et magna. Tempor quis et duis velit excepteur minim. Enim voluptate eu eiusmod et occaecat. Ex occaecat magna cillum pariatur commodo ipsum et. Veniam ex enim dolor cillum ipsum qui eiusmod est velit irure minim in.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39474298e212b8eeea",
    "name": "Xixan expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Monique Stone",
    "description": "Laborum qui deserunt occaecat anim velit. Amet dolore non tempor laboris culpa nisi nulla adipisicing amet ipsum irure quis reprehenderit. Dolor nisi nulla aliqua in nostrud cupidatat commodo id. Consectetur amet labore incididunt mollit sint mollit id cupidatat irure. Est consectetur amet ea in et cillum aliquip officia deserunt.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39e8a66b744c75105d",
    "name": "Comvey expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Georgia Le",
    "description": "Velit nostrud minim nisi id ullamco ipsum deserunt aliquip laboris eiusmod ullamco deserunt quis. In sit irure magna ea culpa do sint laboris. Et culpa pariatur mollit laborum. Labore in eiusmod duis laborum reprehenderit irure minim nulla ullamco.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39ff7f6292969c008d",
    "name": "Codax expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Lourdes Glover",
    "description": "Est duis laboris commodo commodo incididunt. Non est tempor officia nostrud culpa tempor. Aliquip elit sint nulla veniam aliqua anim aute commodo nostrud pariatur cupidatat officia amet pariatur. Deserunt consectetur exercitation irure mollit occaecat est pariatur dolore. Ad occaecat in sunt duis. Laborum laborum elit sunt exercitation non.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b391b0b27e29b5d48a7",
    "name": "Endicil expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Williamson Cervantes",
    "description": "Irure aliquip aute cupidatat voluptate velit eiusmod dolor fugiat velit. Deserunt consectetur enim do consectetur enim incididunt adipisicing do anim cupidatat. Fugiat veniam dolore culpa laborum consectetur aute cupidatat ad cupidatat in consectetur enim. Mollit nostrud elit magna et ullamco ea sint quis. Laborum nulla ad exercitation enim do.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39e923d5bd11dd9484",
    "name": "Geeknet expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Anthony Gonzalez",
    "description": "Eu aute ad consequat sint tempor proident labore veniam. Dolore laboris adipisicing anim occaecat aliquip incididunt esse nostrud cupidatat ipsum. In amet incididunt nulla id do fugiat non ea ex magna. Dolor ea in amet dolor. Officia aute anim consectetur incididunt qui dolor magna id ex nulla velit est. Aliqua irure Lorem esse in sunt ut aliquip qui nulla minim et qui dolore occaecat.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39dfc2060a504119c5",
    "name": "Junipoor expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Noel Brock",
    "description": "Cupidatat non nisi nulla in eiusmod pariatur veniam ullamco dolor eiusmod ut. Esse officia aute ad mollit est qui veniam minim non Lorem velit eu. Mollit exercitation irure ex ullamco. Laborum sunt ad anim amet eu. Et nostrud consequat magna ullamco veniam velit laboris duis cupidatat cillum cillum exercitation magna. Consequat aliqua cupidatat in incididunt dolore aliqua in elit et.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b390e9090eaad8e40b6",
    "name": "Balooba expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Dale Buckner",
    "description": "Esse magna tempor dolore consectetur ullamco laborum sit ut veniam anim. Duis sit ea magna est excepteur commodo amet sit. Nostrud qui excepteur sint id reprehenderit amet Lorem fugiat. Consequat fugiat velit sunt aliquip dolor labore dolor proident. Aliquip tempor consequat exercitation est enim pariatur nulla velit mollit ipsum magna minim sint ex. Proident occaecat labore voluptate mollit est.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39c20458ab90451825",
    "name": "Vixo expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Ivy Hale",
    "description": "Laboris nulla laboris qui pariatur Lorem fugiat ad magna exercitation sit Lorem laborum irure. Deserunt in Lorem nulla deserunt consequat pariatur amet occaecat aliquip. Voluptate ullamco laboris pariatur cupidatat pariatur. Duis sit sunt quis pariatur nulla in laborum ipsum deserunt in.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3908bed97ad6e25eaa",
    "name": "Quintity expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Mckay Wise",
    "description": "Aute magna pariatur cupidatat deserunt Lorem ut commodo aliquip eu. Velit mollit eiusmod et sunt ad quis ipsum esse ullamco. Adipisicing sunt reprehenderit et eu sint incididunt consectetur duis fugiat incididunt duis. Anim esse esse cupidatat aliqua voluptate cillum culpa qui. Nulla proident minim consectetur do reprehenderit eiusmod cillum ex ad labore in est. Duis tempor mollit commodo veniam officia excepteur ad labore aliqua est qui. Adipisicing consequat Lorem qui anim Lorem.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39f4faf69f53bb4fb9",
    "name": "Zaya expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Jeanne Bush",
    "description": "Exercitation officia adipisicing laborum nulla ea. Exercitation esse reprehenderit occaecat dolor velit Lorem magna est reprehenderit nulla aute qui. Non commodo amet voluptate cillum.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39faea40acf8db780b",
    "name": "Venoflex expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Thelma Ramirez",
    "description": "Reprehenderit pariatur nostrud velit officia consequat adipisicing id sunt veniam veniam. Fugiat do pariatur tempor adipisicing reprehenderit tempor commodo esse aliquip ullamco incididunt laborum. Tempor consectetur eu occaecat proident anim cupidatat velit qui ut sit ipsum amet. Et mollit fugiat duis aliquip voluptate tempor reprehenderit ex consequat mollit fugiat fugiat ea magna. Dolore et qui nisi ad amet excepteur enim. Labore occaecat laboris Lorem amet consequat velit est adipisicing.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b392808333ae3bea458",
    "name": "Locazone expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Leigh Greer",
    "description": "Lorem amet cupidatat proident commodo deserunt. Deserunt in elit magna commodo do. Labore incididunt enim nisi mollit Lorem magna tempor id voluptate. Proident reprehenderit dolore ad qui incididunt esse Lorem incididunt fugiat nostrud aliquip. Amet incididunt ut laboris amet.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39c670525fae02b1f7",
    "name": "Hinway expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Blake Camacho",
    "description": "Reprehenderit pariatur ex magna consequat eiusmod commodo laborum id. Adipisicing quis minim laboris pariatur quis nisi ut magna tempor magna. Deserunt ex proident sint commodo ex consectetur velit quis magna reprehenderit voluptate. Exercitation esse magna aute esse laboris sunt.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39a4a85fd22d6244cc",
    "name": "Macronaut expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Lilian Rojas",
    "description": "Deserunt cillum culpa dolor cillum. Ex laboris qui dolor quis elit esse consectetur labore non ex ullamco elit ipsum. Non aute eiusmod sint do pariatur ea exercitation excepteur qui minim excepteur excepteur aute amet. Nisi enim velit consectetur cillum esse. Deserunt nulla magna deserunt sunt anim adipisicing eiusmod ipsum nisi qui irure pariatur. Eu adipisicing esse reprehenderit sunt nulla laborum reprehenderit aute exercitation.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39042e80962bd3379d",
    "name": "Oceanica expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Trina Wiggins",
    "description": "Magna sit nisi proident in non eiusmod tempor aliqua non sint. Anim et consectetur consequat cupidatat ea anim sit laboris. Qui incididunt laboris enim aliquip dolore sit exercitation laboris labore. Cillum velit ea eu nulla excepteur nisi sit dolore do Lorem ipsum qui officia. Est id pariatur adipisicing id sit. Pariatur culpa minim mollit fugiat labore. Qui est culpa qui elit pariatur ut eu est pariatur nisi sint ullamco non ipsum.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b396e083a6dc0044315",
    "name": "Sulfax expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Marjorie Cantrell",
    "description": "Amet quis eiusmod voluptate id exercitation aute minim anim ullamco. Nisi in occaecat reprehenderit nostrud minim ipsum magna excepteur voluptate ea mollit quis labore. Ea exercitation anim qui elit culpa consectetur exercitation non irure tempor ut sunt. Elit do laborum adipisicing incididunt minim aute excepteur ad. Pariatur culpa magna deserunt aute veniam ipsum id exercitation sint consequat excepteur cupidatat. Aute nulla excepteur eiusmod ex ea ipsum voluptate. Velit consectetur commodo cillum ad mollit aliquip id reprehenderit id.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39b5de8fba5ddf6d65",
    "name": "Updat expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Brittany Graham",
    "description": "Qui incididunt et ut est eu. Id cillum dolore consequat ad voluptate occaecat laboris culpa duis. Esse tempor amet dolore esse Lorem amet dolor commodo sit ipsum mollit. Amet qui adipisicing culpa laborum enim. Non ea aliquip culpa id irure eiusmod sunt Lorem. Commodo in sint aliqua in proident et ea amet in ex.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39e1fdb4677e3aa9f8",
    "name": "Vinch expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Koch Peters",
    "description": "Ipsum ex irure commodo aliquip aliquip excepteur ex. Excepteur duis ex est mollit voluptate incididunt ut. Excepteur aliqua ut eu aliquip eu incididunt excepteur ut voluptate esse culpa consectetur ad. Laborum esse cillum nostrud culpa laboris do. Eiusmod in ea enim incididunt sint sit sit tempor exercitation consectetur cillum nostrud officia.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39ac3e80977d401389",
    "name": "Stucco expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Gladys Velasquez",
    "description": "Qui in laboris tempor aliquip eiusmod velit proident veniam. Dolor aute reprehenderit exercitation veniam excepteur culpa et consequat proident ex sint in officia. Anim commodo nostrud nulla ipsum eu labore. Eu consectetur nostrud minim adipisicing laborum. Ex cillum ea do minim laboris minim elit elit labore consequat id sit. Excepteur aliquip adipisicing nostrud cupidatat duis cupidatat esse consectetur sit.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39e01c4d9d8a3d9bc8",
    "name": "Poshome expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Jody Snow",
    "description": "Labore aute anim eu enim nisi duis id est mollit aliqua. Lorem minim sint occaecat nostrud. Labore amet elit dolore nulla non culpa in laborum irure. Enim sit et id consectetur duis laborum elit consequat dolor veniam laboris. Ex ipsum elit dolor consequat ut eu ex excepteur dolore quis voluptate ea est dolore.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3995165862be8ccc83",
    "name": "Zaggle expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Mccray Gaines",
    "description": "Officia sunt in aliquip sunt exercitation deserunt proident est tempor consequat ea. Duis exercitation sit do nostrud Lorem culpa est reprehenderit est voluptate. Aliqua irure aliquip consequat aliquip. Tempor Lorem proident fugiat aliqua ad commodo cillum ex mollit esse esse officia sint minim. Adipisicing nostrud deserunt Lorem id laborum officia fugiat. Quis fugiat Lorem id consectetur est ad ut adipisicing velit est sint do incididunt ut. Pariatur ad commodo ex mollit dolore cillum commodo.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39217b2ac0b246bbe6",
    "name": "Tribalog expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Watson Joyce",
    "description": "Irure commodo esse adipisicing officia reprehenderit dolore laboris mollit. Commodo et eu dolor velit laborum eu eiusmod labore aliquip irure amet ex. Sint exercitation magna elit enim ad ullamco laborum sit fugiat nisi. Voluptate et id adipisicing laboris eu nisi dolore ex non nulla excepteur ut laboris.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3957cea93e2ea52627",
    "name": "Glukgluk expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Beverley Waller",
    "description": "Ullamco minim id fugiat sint in culpa id. Anim fugiat minim eu eiusmod dolor id quis fugiat enim anim ea. Velit pariatur sunt ipsum mollit proident laborum eiusmod excepteur est occaecat adipisicing mollit. Fugiat mollit eu duis nisi consequat reprehenderit aliquip quis Lorem aliquip commodo magna ut.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39c3c63103255ab2b1",
    "name": "Ezentia expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Mabel Hardy",
    "description": "Anim pariatur et commodo irure. Magna eu excepteur culpa ut aute minim ex. Sint do aliqua ut commodo sit nisi sint qui do non amet officia ex tempor. Aliquip proident laboris anim fugiat minim sit magna eiusmod in labore id magna amet. Enim officia reprehenderit pariatur id. Sunt ut nisi duis consequat minim do amet veniam exercitation voluptate.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39345977d88087f31e",
    "name": "Savvy expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Dolly Smith",
    "description": "Ullamco dolor sint culpa sint sint eiusmod veniam quis commodo. Aliquip cillum minim consectetur voluptate non. Aliquip id fugiat ad elit laborum dolor culpa ex proident sunt.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3948f8460f16ace755",
    "name": "Isologica expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Mayer Joyner",
    "description": "Duis exercitation consequat excepteur magna ex consectetur dolore ea non in minim. Commodo officia voluptate enim non id ad fugiat ipsum ad. Est non enim veniam nostrud reprehenderit do.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b398e87c3011e3f88bf",
    "name": "Digiprint expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Dionne Mercado",
    "description": "Occaecat amet non sunt irure officia in. Proident magna minim ad aliqua eu dolore elit consequat. Dolore commodo commodo duis esse irure do quis. Aliquip labore duis pariatur eiusmod id elit mollit. Mollit aliqua laborum quis amet ut.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3914e81ad4a0da89c0",
    "name": "Visalia expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "April Frye",
    "description": "Sunt irure amet non dolore fugiat fugiat consectetur sunt do dolore. Eiusmod voluptate consequat mollit amet ut velit culpa esse incididunt consectetur sint. Exercitation nisi aliqua adipisicing cillum aute voluptate duis pariatur velit laboris. Consequat ex adipisicing laboris Lorem voluptate elit proident mollit est adipisicing.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39a9e9da8f9e0a0790",
    "name": "Quantalia expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Pruitt Finley",
    "description": "Magna non in irure mollit dolor proident incididunt nulla ex cupidatat reprehenderit. Id ipsum nostrud elit adipisicing qui consequat. Sint magna ad fugiat est.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b395c23dd6641900f6c",
    "name": "Syntac expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Harris Church",
    "description": "Ullamco enim exercitation deserunt officia mollit quis deserunt cillum. Incididunt esse eu occaecat mollit ea minim id sit sunt ipsum. Excepteur ad dolore fugiat ullamco minim tempor irure quis duis excepteur do eiusmod. Elit velit laboris velit voluptate id ea est officia ut. Incididunt consectetur aute dolor dolore fugiat reprehenderit eiusmod.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39ff0e3665d795e49c",
    "name": "Inrt expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Lindsay Stewart",
    "description": "Voluptate ea aute anim est minim occaecat. Consectetur proident ipsum minim ad duis exercitation aliquip est id ut nulla. Consequat ullamco excepteur commodo adipisicing mollit exercitation deserunt. Laborum ex et velit do minim tempor excepteur commodo id. Mollit ut quis consectetur irure eiusmod et. Cupidatat anim dolor et laborum nulla nisi laborum do.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b393a30cdef0e6b9eb6",
    "name": "Pyramax expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Blackwell Cohen",
    "description": "Nostrud adipisicing est commodo magna non. Elit culpa nostrud nulla nisi dolore Lorem cupidatat occaecat aliquip nulla. Anim dolor non Lorem elit anim irure amet. Veniam ut aliqua aute incididunt officia pariatur anim. Reprehenderit ex deserunt cillum do commodo non pariatur consequat laboris aute ipsum dolore. Duis eiusmod irure consequat ad adipisicing nostrud consectetur nulla nisi.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b391d2846339e80e6a3",
    "name": "Zerbina expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Camille Wilder",
    "description": "Et fugiat tempor proident incididunt minim enim sunt id eu ipsum nulla. Deserunt laborum cillum nisi ea dolore veniam minim. Id do velit enim sit consectetur pariatur amet ullamco consectetur officia ullamco.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39a7a4bea92bba4166",
    "name": "Fuelworks expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Stuart Richards",
    "description": "Anim sit nulla dolor pariatur. Et labore in dolor sint elit cupidatat aliqua mollit nulla nostrud Lorem exercitation amet. Sit nulla cillum minim aliqua non duis elit. Quis aliqua veniam minim ullamco ex. Et ut aute esse commodo ullamco. Est labore consectetur consectetur mollit nisi ea aliquip non amet voluptate ea do.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b393f6697ae7b6aab71",
    "name": "Hairport expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Leila Bates",
    "description": "Nisi est ut id duis elit nisi dolor officia deserunt. Anim ipsum tempor proident fugiat in. Sint duis exercitation tempor laboris elit. Nisi dolor sunt ea Lorem aliquip voluptate elit. Non amet eiusmod est id sit reprehenderit.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b390464ac2d622a5327",
    "name": "Limage expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Booth Strickland",
    "description": "Cupidatat nisi aliqua eu reprehenderit sunt non consectetur commodo velit sit cupidatat tempor ullamco non. Laborum dolor laboris commodo ex minim ad duis officia culpa mollit. Deserunt ad veniam anim ullamco eiusmod ipsum dolor dolor magna velit labore cillum nulla. Officia sint anim ipsum aliquip eiusmod do culpa nostrud fugiat ullamco.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b395ddd7b43ed9c37ad",
    "name": "Qimonk expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Mandy Hoffman",
    "description": "Ipsum quis id aliqua voluptate proident. In voluptate tempor in enim sit enim ex ullamco minim proident esse enim. Consectetur sunt occaecat enim dolore laborum nisi irure nisi dolore Lorem enim qui. Anim ullamco dolore deserunt dolore ad laboris sunt sit. Magna id proident reprehenderit aliqua laborum enim adipisicing enim veniam id eu.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39302925a1e060b179",
    "name": "Voipa expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Savage Foster",
    "description": "Lorem anim nostrud dolor est cupidatat voluptate proident non non anim ut nostrud minim nulla. Eiusmod incididunt proident irure Lorem magna anim laborum amet proident. Consequat in id aute culpa ad tempor reprehenderit ullamco est exercitation sunt exercitation. Mollit tempor nostrud elit sit consectetur consectetur consectetur consectetur laborum amet cillum irure. Cupidatat ut dolor deserunt eiusmod deserunt fugiat esse. Reprehenderit ipsum deserunt fugiat elit consequat. Incididunt elit quis proident tempor amet quis eiusmod minim excepteur sunt ea fugiat deserunt nulla.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3981a9d344d6e3a05e",
    "name": "Deminimum expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Clay Rosario",
    "description": "Adipisicing aliqua amet sint fugiat consectetur deserunt dolor voluptate reprehenderit laboris eiusmod est proident minim. Lorem consequat est ad commodo laboris ea quis ea qui id est labore. Enim fugiat aute dolor amet. Proident non nulla dolor id aliquip id sunt ad dolor sunt irure irure est et.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b392dc3399039009da6",
    "name": "Autograte expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Kara Ortiz",
    "description": "Sunt ex ipsum tempor laborum ad culpa nostrud do veniam. Ad magna qui velit dolor qui quis in deserunt ex. Laborum do dolore exercitation ullamco veniam irure. Est mollit ex aute cupidatat minim ex pariatur dolore commodo et. Tempor ad tempor eiusmod elit mollit ut. Magna adipisicing esse exercitation nisi eu Lorem eu dolore culpa eu cillum tempor ullamco aute. Labore magna quis fugiat duis laborum incididunt.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39a65409feb498e2e9",
    "name": "Magnina expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Kaufman Gilmore",
    "description": "Id deserunt consequat sunt aliqua ex sint do enim ipsum velit. Qui tempor do nulla minim sit anim. Consectetur velit sunt mollit est in occaecat exercitation aliquip pariatur mollit aute nostrud fugiat.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39e90cca4730f16280",
    "name": "Edecine expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Carole Suarez",
    "description": "Culpa non commodo ullamco amet incididunt fugiat ea ut esse eu culpa. Esse anim in magna fugiat. Ipsum culpa labore et nisi aute nostrud consequat aliquip qui tempor veniam proident ea laboris. Enim officia elit qui amet eiusmod anim.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39867ffbfd4dcff23d",
    "name": "Zenthall expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Lessie Contreras",
    "description": "Consequat commodo deserunt laboris do elit. Ullamco id exercitation nulla aliqua voluptate. Deserunt fugiat et excepteur officia nostrud adipisicing sunt magna in adipisicing aliquip. Minim id occaecat reprehenderit non irure est esse magna aliquip nostrud nostrud ut.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3936821a1018a3a8ef",
    "name": "Fangold expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Washington Marshall",
    "description": "Dolore aute eiusmod cillum laborum. Irure id aute nostrud reprehenderit do nulla culpa do quis ad in non. Consequat est enim do veniam. Aliqua officia dolore nisi irure. Labore Lorem reprehenderit ad aute. Sunt nostrud aute magna ullamco amet.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b395d103f576fffac82",
    "name": "Plexia expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Jocelyn Good",
    "description": "Sit adipisicing nisi anim nulla sunt nulla consectetur ut eiusmod veniam eu ut. Consequat elit consequat cillum aute nulla dolor. Esse aliqua esse veniam amet deserunt elit anim deserunt ad ut. Consequat in ad occaecat nulla.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b393568217d73085227",
    "name": "Krog expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "James Alvarez",
    "description": "Id consequat mollit dolore ad magna. Culpa culpa consectetur aute adipisicing ullamco occaecat laboris amet nostrud incididunt sint minim. Irure qui exercitation et ullamco deserunt dolor elit et non ad sunt adipisicing. Nostrud id commodo incididunt non sunt pariatur ex eiusmod aliqua adipisicing proident consequat excepteur. Fugiat occaecat esse aute irure duis eu anim labore reprehenderit amet duis. Eu ut mollit laboris eiusmod quis ipsum deserunt dolore et laboris. Enim veniam sunt aute nulla laborum deserunt magna non nostrud ullamco officia duis anim nisi.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b396fe1b8445422b009",
    "name": "Ersum expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Morrison Kidd",
    "description": "In ea voluptate mollit eu tempor labore excepteur ea commodo reprehenderit in incididunt ut. Incididunt mollit aliqua excepteur magna occaecat fugiat eiusmod anim. Veniam fugiat Lorem incididunt enim veniam. Do eu ut id sint eu excepteur excepteur proident ut cupidatat. Esse quis proident amet pariatur deserunt culpa nostrud.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39f06bf94f346f8c9f",
    "name": "Comtrak expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Beulah Robles",
    "description": "Elit est velit minim enim consectetur eiusmod commodo in sint officia officia cupidatat. Cillum cupidatat proident irure sit labore. Elit proident ullamco commodo magna id. Est culpa ex irure deserunt. Proident laborum laborum tempor non laborum duis consectetur ipsum.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39f437e7f88191ae71",
    "name": "Playce expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Alison Jimenez",
    "description": "Minim et ipsum sit est pariatur ea quis amet cillum id dolor. Consectetur commodo eu Lorem velit ut aliqua ut dolore cillum commodo. Cillum nisi nostrud irure Lorem laboris amet velit elit. Mollit nostrud sit pariatur laborum. Minim nulla et magna exercitation aliqua eiusmod dolore voluptate deserunt sit velit. Consectetur mollit ipsum amet est laboris minim cupidatat irure esse. Nisi quis dolore dolore enim reprehenderit aliqua fugiat esse excepteur nisi nostrud.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3976d5038e2120dcc7",
    "name": "Plasmos expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Gibbs Ramsey",
    "description": "Dolore qui magna id amet laboris aliquip laboris. Adipisicing adipisicing consectetur duis id cupidatat qui veniam adipisicing dolor quis tempor. Anim cillum nisi magna excepteur ipsum proident esse dolor anim aute nostrud non ad nulla. Reprehenderit veniam consequat veniam est voluptate dolore voluptate commodo laboris Lorem laborum.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39b2f2ef272c3216ee",
    "name": "Xumonk expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Murray Trevino",
    "description": "Mollit laborum amet laborum ea non labore ad eiusmod Lorem. Aliqua ex sit tempor qui adipisicing commodo id velit Lorem consequat. Minim mollit Lorem adipisicing voluptate magna nulla consequat est. Proident labore reprehenderit incididunt dolor. Dolore aute reprehenderit quis Lorem voluptate do non proident consectetur pariatur ex magna. Anim laborum incididunt aliquip ipsum laborum commodo officia sit magna ipsum culpa.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39f645e7d4428b89bd",
    "name": "Tellifly expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Melendez Patton",
    "description": "Qui duis culpa commodo ullamco incididunt sunt proident. Reprehenderit incididunt excepteur nisi est anim velit laboris. Tempor cupidatat sint mollit qui id pariatur veniam aliquip dolore magna voluptate. Nulla dolore aute ad ipsum non. Ipsum cillum ut eiusmod sint culpa. Eu aute cupidatat veniam nulla occaecat.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39494ea66a9ae36995",
    "name": "Kindaloo expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Alta Wheeler",
    "description": "Non sunt in fugiat proident ea. Tempor cillum ex cupidatat minim in quis esse excepteur ad. Ut cillum elit fugiat anim ad laboris. Sit et velit aliqua consequat exercitation non duis in. Quis mollit et nisi id sint consectetur labore mollit labore. Nulla voluptate id minim ad.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3953629431b0fd2005",
    "name": "Medicroix expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Emilia Rice",
    "description": "Pariatur dolore in elit deserunt sint laboris irure in. Esse proident officia et labore elit in do do dolor anim qui. Labore veniam excepteur dolore sint ipsum adipisicing mollit nulla ipsum ipsum. Nisi qui mollit aute exercitation occaecat enim.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39e0d7d1ea5f35dc04",
    "name": "Utarian expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Dorsey Deleon",
    "description": "Adipisicing excepteur fugiat in elit cupidatat aliquip non enim. Adipisicing duis id esse enim sint labore enim dolor fugiat fugiat dolore enim velit duis. Elit et officia mollit exercitation id dolor sunt nostrud aliquip. Labore in mollit occaecat minim ea occaecat sit. Ullamco aute velit excepteur quis aliquip sint velit dolore officia consectetur deserunt. Id laborum esse culpa consectetur laborum nostrud amet. Officia velit minim minim velit nisi aute duis ipsum enim est occaecat.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39c1efcca8558e75ad",
    "name": "Exerta expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Clarice Nixon",
    "description": "Labore ad reprehenderit ullamco culpa. Sunt consequat Lorem ex occaecat irure occaecat culpa consectetur id non tempor tempor. Consectetur occaecat nulla ea sit ea pariatur in. Sunt deserunt sint Lorem est mollit cupidatat qui ad ipsum nostrud esse excepteur. Deserunt aliquip voluptate ullamco nostrud dolor.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3909a08fb0ab3f54d0",
    "name": "Lyria expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Campbell Fuller",
    "description": "Velit dolor mollit nostrud exercitation eu minim. Enim laboris amet consectetur tempor occaecat minim velit. Quis aliqua pariatur voluptate Lorem culpa eu. Irure officia cupidatat officia ea. Officia non duis commodo voluptate duis enim.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39027369a132bcffe5",
    "name": "Daycore expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Jewel Nicholson",
    "description": "Enim laboris consequat irure qui ex. Ipsum reprehenderit id velit consequat officia consectetur ea fugiat proident duis aliqua proident aliqua. Aute cupidatat sint laboris velit minim officia. Sunt minim excepteur amet ex aliquip amet ut ad enim Lorem non. Culpa excepteur do aliqua reprehenderit. Officia ad adipisicing dolore commodo nulla id veniam incididunt amet non ullamco pariatur ex.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3951f556a1a67ebe66",
    "name": "Zenco expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Conrad Acosta",
    "description": "Minim cupidatat eiusmod fugiat sit duis do deserunt tempor ipsum cillum. Voluptate ullamco commodo est proident magna sint quis sit. Proident aliquip excepteur fugiat aliquip quis dolor labore velit quis mollit dolore.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b395270aa476cd64f3d",
    "name": "Zinca expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Paul Goodwin",
    "description": "Id nisi quis fugiat non sit id officia enim qui sint in sint. Quis do labore adipisicing ut laboris veniam anim nulla. Sunt laboris dolor do sint nulla eu nostrud incididunt cupidatat amet. Sunt enim occaecat culpa exercitation commodo. Nulla fugiat occaecat fugiat id ea proident velit adipisicing mollit ad duis.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b392b1fd8435b8c07bb",
    "name": "Netagy expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Herminia Luna",
    "description": "Sunt incididunt et eu consequat incididunt velit commodo anim excepteur qui id ea mollit ullamco. Cillum aute consectetur est quis sit. Et aliqua duis tempor elit voluptate qui fugiat. Occaecat ad elit minim non sit laborum veniam do non consequat sunt.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39e5f5b88ed82b3089",
    "name": "Idealis expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Curtis Kramer",
    "description": "Ex et amet ea proident ea non sit. Deserunt velit officia voluptate ut anim aute aliqua pariatur in nulla duis ea fugiat. Enim exercitation velit excepteur laboris occaecat ex voluptate laborum aliqua aute veniam.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39251b77c9b2dda8f8",
    "name": "Accuprint expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Coffey Hinton",
    "description": "Exercitation amet velit ea non officia. Pariatur pariatur eiusmod cillum nisi est dolore. Proident est laborum ipsum sunt sint excepteur Lorem quis magna. Eiusmod amet exercitation amet qui exercitation aute do consequat incididunt pariatur cillum. Ut cillum duis deserunt esse excepteur aliquip voluptate officia incididunt. Tempor do veniam minim consectetur et irure non consectetur.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3946d59f9aafd9edba",
    "name": "Zillacon expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Velma Stark",
    "description": "Ullamco aliquip dolore aute minim sunt duis incididunt veniam consequat ipsum in eiusmod quis id. Ex officia id consequat velit duis sit ipsum voluptate nostrud sint ea. Qui ex qui consectetur est elit ex sunt ipsum labore nostrud voluptate nostrud. Ea in ad sunt laboris magna ipsum velit et laboris tempor deserunt. Laboris duis aute incididunt labore eiusmod amet velit commodo excepteur veniam excepteur. Do ipsum aliqua aliqua et cillum. Aliqua deserunt deserunt irure non quis ut incididunt tempor irure ullamco eu.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3991d3452bfcc0654a",
    "name": "Menbrain expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Gena Glass",
    "description": "Fugiat veniam nostrud commodo labore incididunt officia excepteur voluptate pariatur. Do ullamco cupidatat quis in exercitation magna anim sint et voluptate culpa consequat. Quis fugiat aliquip occaecat nostrud cillum qui in voluptate Lorem id aliquip laboris do ipsum. Mollit exercitation nulla fugiat excepteur minim consectetur officia aliqua occaecat excepteur magna culpa dolor aliqua. Voluptate velit magna dolor anim qui et ex irure dolore do.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39459bdcef087b63e2",
    "name": "Lovepad expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Sherrie Franco",
    "description": "Labore Lorem dolore ad occaecat nostrud dolor anim ea tempor anim. Irure laboris ex laboris Lorem excepteur deserunt cillum qui. Non qui mollit ea nisi quis eu excepteur sint Lorem quis tempor incididunt.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3997c24cd84dd0e386",
    "name": "Handshake expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Marianne Morgan",
    "description": "Ea dolore laboris laboris esse nostrud. Laboris Lorem nostrud ad sint ad officia pariatur elit. Aliqua labore adipisicing minim magna proident. Exercitation magna sit nulla sit ea tempor incididunt pariatur magna.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3998894ca1149f5d7b",
    "name": "Calcu expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Heath Valdez",
    "description": "Eu Lorem cillum nostrud velit est consectetur elit ut aliquip cillum. Fugiat enim mollit elit minim incididunt. Ex pariatur dolore ipsum Lorem reprehenderit Lorem. Lorem cillum incididunt ullamco et. Sint esse pariatur nisi quis cillum nisi culpa nostrud veniam. In id voluptate veniam nostrud ex ut. Non commodo sit ea do tempor cupidatat non Lorem eiusmod esse sint tempor Lorem.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39c63469c104db5a9e",
    "name": "Lumbrex expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Elnora Pope",
    "description": "Sit cillum mollit in ut laboris dolore do eu. Consequat incididunt officia aliquip deserunt. Minim ex Lorem Lorem labore occaecat incididunt minim duis id. Ad proident commodo in minim elit tempor incididunt in officia et nulla voluptate Lorem. Quis irure nulla proident occaecat et labore sunt et duis consectetur aliqua exercitation.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3913e19823f4725e6f",
    "name": "Comdom expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Acosta Johnson",
    "description": "In minim incididunt exercitation deserunt occaecat nostrud exercitation fugiat fugiat ea esse elit labore. Fugiat in non anim mollit fugiat cillum ea magna elit qui nisi. Commodo sunt pariatur culpa dolore fugiat ad pariatur ullamco dolor enim aute exercitation. Aliqua do dolore aliquip voluptate sunt laboris duis labore mollit aliqua. Deserunt eiusmod amet officia tempor fugiat nisi quis irure sint. Adipisicing consectetur sit culpa anim non nulla ex enim est excepteur voluptate labore ea tempor. Culpa do enim incididunt in.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39764d43631f4fa22a",
    "name": "Applideck expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Yvonne Ferguson",
    "description": "In id pariatur in consequat. Proident incididunt culpa ut nostrud nisi Lorem minim esse reprehenderit quis. Laboris nulla amet fugiat nulla enim ullamco ad occaecat mollit. Tempor consectetur id consectetur consectetur sunt reprehenderit anim proident id aute quis veniam. Commodo adipisicing sint aute ea cillum non adipisicing. Ullamco veniam sint aliqua do ad culpa mollit ipsum Lorem.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b398c05d9137e05abc7",
    "name": "Candecor expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Julia Potter",
    "description": "Duis fugiat veniam irure nostrud nostrud. Culpa nisi voluptate ad in. Est ea duis consequat amet elit velit tempor dolor exercitation ad adipisicing. Adipisicing esse est ipsum culpa. Pariatur laboris mollit eiusmod mollit consequat non commodo anim deserunt. Ea exercitation veniam adipisicing veniam sint adipisicing. Duis pariatur velit cupidatat tempor excepteur culpa officia ut.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b396147c5d1a1bf4483",
    "name": "Slax expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Leona Erickson",
    "description": "Laboris duis pariatur dolor non officia laborum do deserunt qui dolor sint eiusmod do quis. Sunt laborum amet minim ad dolor. Sunt velit fugiat veniam ex nostrud eiusmod in esse labore dolor. Tempor excepteur anim ex ipsum minim velit consequat non dolore in labore proident fugiat. Sit proident incididunt labore minim Lorem duis culpa sit.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39366776062733b7d7",
    "name": "Steeltab expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Lowe Hubbard",
    "description": "Lorem irure do sunt eiusmod aliquip proident pariatur laborum do. Velit voluptate aliqua qui in eu consectetur laboris esse est. Eu sunt laboris pariatur consectetur ipsum. Voluptate nisi officia laborum eiusmod et fugiat eu Lorem.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39e782ca89b8ba01fd",
    "name": "Isosphere expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Valerie Stout",
    "description": "Amet sunt cupidatat do cillum sit aliqua minim voluptate irure enim duis consectetur voluptate. Do consectetur nisi consectetur esse. Est sunt duis ad veniam irure aliquip est. Aute nulla nostrud et voluptate consectetur tempor qui velit. Aliqua non fugiat excepteur ea.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39eed555cec52b80bf",
    "name": "Aquazure expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Morris Waters",
    "description": "Nostrud est labore id elit minim consectetur laboris. Quis est irure quis pariatur ipsum anim eiusmod dolor non ut dolore veniam Lorem veniam. Amet cupidatat elit fugiat fugiat irure. Pariatur culpa id cillum nulla eiusmod nisi Lorem incididunt. Sunt et mollit sit non labore irure proident sunt. Mollit culpa culpa aliqua magna incididunt Lorem.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b390fcbd084905d74d8",
    "name": "Verbus expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Hester Fleming",
    "description": "Tempor ut minim velit incididunt tempor duis id excepteur enim labore ipsum. Do pariatur sint pariatur do ut eiusmod Lorem exercitation culpa veniam sit consectetur irure dolor. Culpa enim fugiat sit sunt excepteur. Cupidatat quis exercitation sunt sunt elit tempor ad incididunt. Non aliqua Lorem laboris enim officia. Consequat ipsum magna non anim irure reprehenderit minim cillum proident ad.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b393b01e8bdda47afba",
    "name": "Neocent expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Jenny Noble",
    "description": "In anim elit non minim reprehenderit est id ad anim ad commodo eiusmod nostrud laborum. Ea Lorem in in pariatur in. Occaecat eiusmod quis officia ex commodo et sit minim ipsum.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39d75646d2d5ff7102",
    "name": "Boilicon expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Loretta Anderson",
    "description": "Magna duis cillum eu et est laboris sint ut amet ea in Lorem. Exercitation proident elit aliqua id qui dolor eu. Eiusmod mollit non in sunt aliqua dolore est sunt occaecat voluptate. Anim ad Lorem id aute adipisicing consequat dolor Lorem culpa. Lorem ad anim nisi elit magna cillum enim elit fugiat minim ut ullamco.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b393f90ad0e904e177e",
    "name": "Skyplex expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Sargent Dixon",
    "description": "Qui aute tempor mollit aliqua. Commodo amet elit incididunt commodo aute ea. Officia adipisicing laboris sunt occaecat nisi. Fugiat non reprehenderit in id. Incididunt anim sint ex pariatur qui deserunt excepteur ipsum. Aliquip mollit excepteur magna tempor do sit sunt.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39e8129e0f3ac5eb1d",
    "name": "Tripsch expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Pauline Mclean",
    "description": "Dolor Lorem incididunt sint nulla minim commodo proident aliqua qui deserunt. Aliqua laborum sint laboris nulla sint commodo deserunt elit ut. Exercitation velit consequat sint voluptate mollit in. Nisi fugiat id pariatur et consectetur ad. Ex ad occaecat exercitation nulla enim officia ullamco est ex commodo labore occaecat. Consequat minim non quis fugiat.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39d103c939b6008698",
    "name": "Xth expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "June Flynn",
    "description": "Sint proident sunt dolore culpa velit ex et duis velit excepteur sunt voluptate sunt. Ut ex ea incididunt voluptate pariatur aliqua exercitation cupidatat elit duis magna Lorem fugiat esse. Fugiat fugiat duis ut minim laborum consequat laboris.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39c0e25a0add0866bc",
    "name": "Providco expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Marcella Zimmerman",
    "description": "Elit consectetur consequat esse laborum duis duis do ullamco ea fugiat anim amet ullamco. Voluptate in incididunt minim amet adipisicing pariatur consectetur cupidatat incididunt eiusmod. Amet cillum duis consequat reprehenderit ut adipisicing officia fugiat veniam in cillum. Officia dolore nostrud eiusmod excepteur. In esse mollit nulla enim labore voluptate irure veniam reprehenderit do esse elit deserunt tempor. Ex laboris aliquip incididunt voluptate culpa voluptate. Aliquip voluptate veniam anim consequat do in ullamco Lorem magna irure.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b3961a4b647ad6c6989",
    "name": "Quiltigen expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Stevens Goff",
    "description": "Veniam nostrud fugiat consectetur esse eu laborum. Esse commodo id aute amet exercitation eu officia laborum adipisicing est duis. Eu adipisicing adipisicing consequat tempor consequat aliqua proident voluptate. Do ipsum eiusmod cillum proident officia et. In cillum minim aliquip elit eu tempor eu anim ullamco. Commodo dolore sunt eu commodo velit eiusmod. Amet consequat tempor qui sit in sint.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39c591c3182c499767",
    "name": "Besto expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Merrill Estrada",
    "description": "Lorem exercitation eu enim proident non fugiat mollit cupidatat magna velit id. Occaecat laborum cupidatat adipisicing mollit officia nulla Lorem. Cillum cupidatat in et et consectetur sint ullamco ipsum. Velit sunt pariatur laboris pariatur veniam consequat minim. Irure occaecat elit consectetur eu.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39f53f87a5a1df744a",
    "name": "Zoinage expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Dixie Cox",
    "description": "Velit Lorem exercitation nisi duis nisi sunt sint cillum elit aliqua laborum irure enim sit. Ea ullamco sint duis ad aute in excepteur dolor. Adipisicing dolor nostrud nulla laborum incididunt do. Commodo velit laborum in in fugiat magna eu sit nulla exercitation do sint. Laboris id irure ullamco aute labore. Ad ullamco dolore cillum ullamco. Cupidatat dolore elit velit labore non proident.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b391be93d48c60e16e8",
    "name": "Lexicondo expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Baxter Hester",
    "description": "Consectetur amet anim dolor labore ad. Aliquip sint sunt adipisicing irure aute anim nisi ullamco. Laborum est eiusmod cillum consequat dolor dolore minim laboris eiusmod amet consectetur enim id amet. Sit nisi do duis pariatur deserunt commodo excepteur laborum Lorem est culpa duis.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39edd83d3e11447586",
    "name": "Injoy expo",
    "isLive": false,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Mcfadden Mccarthy",
    "description": "Ad incididunt culpa nisi veniam eu occaecat. Aute nostrud velit aute et ut non elit magna laborum sint esse. Veniam excepteur Lorem culpa anim minim. Fugiat excepteur anim excepteur reprehenderit consequat aliqua quis. Magna minim irure ad nulla minim anim. Est reprehenderit officia excepteur magna ut.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39efa79ca2e4a42167",
    "name": "Steelfab expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Ebony Larson",
    "description": "Adipisicing cupidatat nulla magna ad adipisicing officia adipisicing ad magna esse mollit aute magna. Dolor minim enim consequat ex. Dolore voluptate laborum est ea ad adipisicing. Do non nostrud cupidatat eu commodo duis nisi est dolor mollit. Ipsum sint ad pariatur excepteur do minim commodo ullamco culpa proident sunt voluptate ad. Cillum elit eiusmod esse proident amet ex do veniam labore ea laborum fugiat.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  },
  {
    "id": "60397b39e8da888e54f43e8c",
    "name": "Kraggle expo",
    "isLive": true,
    "picture": "https://i.kym-cdn.com/entries/icons/facebook/000/020/983/Cb2OXNBUcAAHakf.jpg",
    "speakerName": "Chavez Harding",
    "description": "Adipisicing culpa ut esse tempor culpa nisi. Irure pariatur velit pariatur ullamco nulla irure voluptate laboris duis veniam labore reprehenderit velit id. Officia qui anim ex est amet. Quis do ut elit sint ad ex deserunt officia laboris tempor esse aliquip cillum non.\r\n",
    "audienceCapacity": 250,
    "audienceCount": 100,
    "dateString": "Thu, 9:00 am to 10:00 am"
  }
];

